version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/webapp
hooks:
  BeforeInstall:
    - location: scripts/CopyCloudWatchConfig.sh
  ApplicationStop:
    - location: scripts/StopApplication.sh
  AfterInstall:
    - location: scripts/RunApplicationAfter.sh
  ApplicationStart:
    - location: scripts/RunApplication.sh
