name: Perform Unit Tests
on:
  pull_request:
    branches: [push]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest test/test_hypedsearch.py
