name: Perform Unit Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          mkdir logs
          touch /opt/resources
          touch logs/records.log
          echo "1" > /opt/resources
          echo "2" >> /opt/resources
          echo "3" >> /opt/resources
          echo "4" >> /opt/resources
          echo "5" >> /opt/resources
          echo "6" >> /opt/resources
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest test_main.py
