name: Perform Unit Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest test_main.py
